[2022-07-28 15:04:19,899][DEBUG|kw_main.py:44] >> window start
[2022-07-28 15:07:23,584][DEBUG|kw_main.py:46] >> window start
[2022-07-28 15:07:31,573][DEBUG|kw_main.py:46] >> window start
[2022-07-28 15:07:42,057][DEBUG|kw_main.py:77] >> 'MyWindow' object has no attribute 'view_selec_coin_lbl'
[2022-07-28 15:07:42,057][DEBUG|kw_main.py:78] >> Traceback (most recent call last):
  File "C:/Users/kdonn/PycharmProjects/pythonProject/testdH/kw_main.py", line 74, in cell_cliked_func
    self.view_selec_coin_lbl.setText(select_code)
AttributeError: 'MyWindow' object has no attribute 'view_selec_coin_lbl'

[2022-07-28 15:39:34,498][DEBUG|kw_main.py:46] >> window start
[2022-07-28 15:44:45,969][DEBUG|kw_main.py:19] >> window start
[2022-07-28 15:47:38,094][DEBUG|kw_main.py:19] >> window start
[2022-07-28 15:47:45,157][DEBUG|kw_main.py:19] >> window start
[2022-07-28 15:48:58,966][DEBUG|kw_main.py:19] >> window start
[2022-07-28 15:52:52,606][DEBUG|kw_main.py:19] >> window start
[2022-07-28 15:56:23,153][DEBUG|kw_main.py:19] >> window start
[2022-07-28 15:57:10,076][DEBUG|kw_main.py:19] >> window start
[2022-07-28 15:59:43,845][DEBUG|kw_main.py:19] >> window start
[2022-07-28 18:49:39,054][DEBUG|kw_main.py:19] >> window start
[2022-07-28 18:52:16,101][DEBUG|kw_main.py:15] >> window start
[2022-07-28 19:17:48,757][DEBUG|kw_main.py:15] >> window start
[2022-07-28 19:37:53,740][DEBUG|kw_main.py:15] >> window start
[2022-07-28 19:39:20,841][DEBUG|kw_main.py:15] >> window start
[2022-07-28 19:39:38,771][DEBUG|kw_main.py:15] >> window start
[2022-07-28 20:02:45,305][DEBUG|kw_main.py:15] >> window start
[2022-07-28 20:18:16,361][DEBUG|kw_main.py:15] >> window start
[2022-07-28 20:18:52,722][DEBUG|kw_main.py:15] >> window start
[2022-07-28 20:19:59,042][DEBUG|kw_main.py:15] >> window start
[2022-07-28 20:22:02,757][DEBUG|kw_main.py:15] >> window start
[2022-07-28 20:22:40,772][DEBUG|kw_main.py:15] >> window start
[2022-07-28 20:35:22,027][DEBUG|kw_main.py:15] >> window start
[2022-07-28 20:50:11,750][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:31:58,597][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:32:30,068][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:34:16,769][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:35:31,893][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:37:24,807][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:40:48,436][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:41:48,273][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:41:52,811][DEBUG|kw.py:185] >> arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments
[2022-07-28 21:41:52,811][DEBUG|kw.py:186] >> Traceback (most recent call last):
  File "C:\Users\kdonn\PycharmProjects\pythonProject\testdH\kw.py", line 183, in SendOrder
    "test_name", "0101", accno  , 1  , code   , amount, 0  , "03", "")
TypeError: arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments

[2022-07-28 21:44:08,759][DEBUG|kw.py:185] >> arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments
[2022-07-28 21:44:08,759][DEBUG|kw.py:186] >> Traceback (most recent call last):
  File "C:\Users\kdonn\PycharmProjects\pythonProject\testdH\kw.py", line 183, in SendOrder
    "test_name", "0101", accno  , 1  , code   , int(amount), 0  , "03", "")
TypeError: arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments

[2022-07-28 21:44:18,507][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:44:21,276][DEBUG|kw.py:185] >> arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments
[2022-07-28 21:44:21,276][DEBUG|kw.py:186] >> Traceback (most recent call last):
  File "C:\Users\kdonn\PycharmProjects\pythonProject\testdH\kw.py", line 183, in SendOrder
    "test_name", "0101", accno  , 1  , code   , int(amount), 0  , "03", "")
TypeError: arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments

[2022-07-28 21:45:49,874][DEBUG|kw_main.py:15] >> window start
[2022-07-28 21:45:54,993][DEBUG|kw.py:185] >> arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments
[2022-07-28 21:45:54,994][DEBUG|kw.py:186] >> Traceback (most recent call last):
  File "C:\Users\kdonn\PycharmProjects\pythonProject\testdH\kw.py", line 183, in SendOrder
    "test_name", "0101", int(accno)  , 1  , code   , amount, 0  , "03", "")
TypeError: arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments

[2022-07-28 21:45:59,502][DEBUG|kw.py:185] >> arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments
[2022-07-28 21:45:59,502][DEBUG|kw.py:186] >> Traceback (most recent call last):
  File "C:\Users\kdonn\PycharmProjects\pythonProject\testdH\kw.py", line 183, in SendOrder
    "test_name", "0101", int(accno)  , 1  , code   , amount, 0  , "03", "")
TypeError: arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments

[2022-07-28 21:47:38,877][DEBUG|kw.py:185] >> arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments
[2022-07-28 21:47:38,877][DEBUG|kw.py:186] >> Traceback (most recent call last):
  File "C:\Users\kdonn\PycharmProjects\pythonProject\testdH\kw.py", line 183, in SendOrder
    "test_name", "0101", int(accno)  , 1  , code   , amount, 0  , "03", "")
TypeError: arguments did not match any overloaded call:
  dynamicCall(self, str, Iterable[Any]): argument 2 has unexpected type 'str'
  dynamicCall(self, str, value1: Any = None, value2: Any = None, value3: Any = None, value4: Any = None, value5: Any = None, value6: Any = None, value7: Any = None, value8: Any = None): too many arguments

[2022-07-28 21:49:30,558][DEBUG|kw_main.py:15] >> window start
[2022-07-28 22:01:07,204][DEBUG|kw_main.py:15] >> window start
[2022-07-28 22:01:25,461][DEBUG|kw_main.py:15] >> window start
[2022-07-28 22:03:35,729][DEBUG|kw_main.py:15] >> window start
[2022-07-28 22:03:58,833][DEBUG|kw_main.py:15] >> window start
[2022-07-28 22:05:05,854][DEBUG|kw_main.py:15] >> window start
[2022-07-28 22:05:43,206][DEBUG|kw_main.py:15] >> window start
[2022-07-28 22:05:56,881][DEBUG|kw_main.py:15] >> window start
